NumStages: 10 # Number of model investment planning stages
StageLengths: [1,1,1,1,1,1,1,1,1,1] # Length of each model stage (years)
WACC: 0.045 # Weighted average cost of capital
ConvergenceTolerance: 0.01 # Relative optimality gap used for convergence
Myopic: 1 # If using multi-stage GenX, 1 = myopic, 0 = dual dynamic programming
